volumes:
    archivebox-data:
    fess-data:
    elasticsearch-data:

services:
    archivebox:
        image: archivebox/archivebox:latest
        command: server --quick-init 0.0.0.0:8000
        expose:
            - "8000"
        ports:
            - "8002:8000"  # 直接アクセス用（オプション）
        environment:
            - ALLOWED_HOSTS=*
            - PUBLIC_INDEX=True
            - PUBLIC_SNAPSHOTS=True
            - PUBLIC_ADD_VIEW=False
            - SAVE_ARCHIVE_DOT_ORG=False
            - SAVE_TITLE=True
            - SAVE_FAVICON=True
            - SAVE_WGET=True
            - SAVE_WARC=True
            - SAVE_PDF=True
            - SAVE_SCREENSHOT=True
            - SAVE_DOM=True
            - SAVE_READABILITY=True
            - SAVE_MERCURY=False
            - SAVE_GIT=False
            - SAVE_MEDIA=False
            - TIMEOUT=60
            - MEDIA_TIMEOUT=120
            - CHECK_SSL_VALIDITY=True
        volumes:
            - archivebox-data:/data
        networks:
            - n8n-compose_default
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.archivebox.rule=Host(`archive.${DOMAIN:-210.131.211.98.nip.io}`)"
            - "traefik.http.routers.archivebox.entrypoints=web,websecure"
            - "traefik.http.routers.archivebox.tls=true"
            - "traefik.http.routers.archivebox.tls.certresolver=mytlschallenge"
            - "traefik.http.services.archivebox.loadbalancer.server.port=8000"
        restart: unless-stopped

    fess:
        image: codelibs/fess:14.17.0
        expose:
            - "8080"
        ports:
            - "8081:8080"  # 直接アクセス用（オプション）
        environment:
            - TZ=Asia/Tokyo
            - FESS_DICTIONARY_PATH=/var/lib/fess/dict/
            - fess_es_http_url=http://elasticsearch:9200
            - fess_es_transport_addresses=elasticsearch:9300
        volumes:
            - fess-data:/var/lib/fess
        networks:
            - n8n-compose_default
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.fess.rule=Host(`search.${DOMAIN:-210.131.211.98.nip.io}`)"
            - "traefik.http.routers.fess.entrypoints=web,websecure"
            - "traefik.http.routers.fess.tls=true"
            - "traefik.http.routers.fess.tls.certresolver=mytlschallenge"
            - "traefik.http.services.fess.loadbalancer.server.port=8080"
        depends_on:
            - elasticsearch
        restart: unless-stopped

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        environment:
            - discovery.type=single-node
            - cluster.name=fess-es
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # 6GB RAMのうち1GBを割り当て
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
            - default
        restart: unless-stopped

networks:
    n8n-compose_default:
        external: true
    default:
        driver: bridge
